version: '3.1'

services:
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        container_name: coodesh_react_app
        restart: unless-stopped
        env_file: .env
        environment:
            - REACT_APP_BASE_URL=$REACT_APP_BASE_URL
        ports:
            - "3000:3000"
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        networks:
            - app-network
        command: yarn start

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: